# CoordsPlugin - copyright @ Gustav Vadstr√∂m 2021

# The Title of the opened inventory "menu"
MenuTitle: "Purchase Player's Coordinates"

# The amount of money required to purchase coordinates.
Price: 1500000

# The title and description of the head displayed as a player.
# %buyer% - The player's name that bought the coordinates.
# %buyer_display% - The buyer's display name.
# %victim% - The victim's name
# %victim_display% - The victim's display name
# %price% - The cost of the item.
ItemTitle: "&3%victim%"

ItemDesc:
  - "&9Price: &a%price%"
  - "&8Click to purchase this player's coordinates"

NotEnoughMoney: "&cInsufficient funds."
PlayerOffline: "&cThat player is no longer online."

# Boolean indicates whether a message should be broadcast to everyone.
Broadcast: true
BroadcastMessage:
  - "&3%buyer% &9Just bought &3%victim%'s &9Coordinates!"

# The message sent when purchase is complete.
# Same as above, but also:
# %worldtype% - What world they are in. Nether,End,Normal
# %x% %y% %z% - Default coordinates
CoordMessage:
  - "&9You purchased &3%name%'s &9coordinates for &a%price%"
  - "&3Coordinates: &c[%worldtype%] X: %x%, Y: %y%, Z: %z%"